export const routes = {
  SPLASH_SCREEN: 'splashscreen',
  LOGIN_SCREEN: 'loginscreen',
  SIGNUP_SCREEN: 'signupscreen',
  GENDERSELECTION_SCREEN: 'genderselection',
  ONBOARD_SCREEN: 'onboardscreen',
  TASKSLECTION_SCREEN: 'taskselection',
  HOME_SCREEN: 'homescreen',
};

export const colors = {
  Primary: '#151B73',
  White: '#FFFFFF',
  Black: '#000000',
  Shadow: '#000',
};

export const Icons = {
  // Icons
  Alarm: require('../assets/icons/alarm.png'),
  Analysis: require('../assets/icons/analysis.png'),
  Arrow: require('../assets/icons/arrow.png'),
  Bell: require('../assets/icons/bell.png'),
  Calendar: require('../assets/icons/calendar.png'),
  Category: require('../assets/icons/category.png'),
  Check: require('../assets/icons/check.png'),
  Clock: require('../assets/icons/clock.png'),
  Flag: require('../assets/icons/flag.png'),
  Home: require('../assets/icons/home.png'),
  Link: require('../assets/icons/link.png'),
  Note: require('../assets/icons/note.png'),
  Notificationoff: require('../assets/icons/notification-off.png'),
  Notification: require('../assets/icons/notification.png'),
  Numeric: require('../assets/icons/numeric.png'),
  Pending: require('../assets/icons/pending.png'),
  Planner: require('../assets/icons/planner.png'),
  Plus: require('../assets/icons/plus.png'),
  Refresh: require('../assets/icons/refresh.png'),
  Ring: require('../assets/icons/ring.png'),
  RoundPlus: require('../assets/icons/round-plus.png'),
  Set: require('../assets/icons/set.png'),
  Settings: require('../assets/icons/settings.png'),
  Tick: require('../assets/icons/tick.png'),
  Time: require('../assets/icons/time.png'),
  Timer: require('../assets/icons/timer.png'),
  Trash: require('../assets/icons/trash.png'),
  Uplift: require('../assets/icons/uplift.png'),

  // Images
  Create: require('../assets/Images/Cateogery/create.png'),
  Faith: require('../assets/Images/Cateogery/faith.png'),
  Growth: require('../assets/Images/Cateogery/growth.png'),
  Health: require('../assets/Images/Cateogery/health.png'),
  Love: require('../assets/Images/Cateogery/love.png'),
  Money: require('../assets/Images/Cateogery/money.png'),
  Other: require('../assets/Images/Cateogery/other.png'),
  Work: require('../assets/Images/Cateogery/work.png'),
  Female: require('../assets/Images/female.png'),
  Goal: require('../assets/Images/goal.png'),
  Habit: require('../assets/Images/habit.png'),
  Male: require('../assets/Images/male.png'),
  Preview: require('../assets/Images/preview.png'),
  Recurring: require('../assets/Images/recurring.png'),
  Task: require('../assets/Images/task.png'),
  Task1: require('../assets/Images/task1.png'),
  Task2: require('../assets/Images/task2.png'),
  Task3: require('../assets/Images/task3.png'),
  Task5: require('../assets/Images/task5.png'),
  Task6: require('../assets/Images/task6.png'),
  Taskhome: require('../assets/Images/taskhome.png'),
  Walk: require('../assets/Images/walk.png'),
  Yogo: require('../assets/Images/yogo.png'),
  Cash: require('../assets/Images/money.png')
};
